### ISSUE TITLE
Linux Agent Support?

### ISSUE THREAD

**Issue by TheFrodo** [tigattack/VeeamNotify#54]
### Describe your ideal solution

Hello all,

Is it actually possible to use the script for the Linux Agent? Since my servers are backed up via the Linux Agent, without a Veeam Backup & Replication Server.

**Comment by tigattack** [comment]
Hi, please the [Agent job support](https://github.com/tigattack/VeeamNotify/blob/main/README.md#agent-job-support) section in the readme, this explains everything about the current state of Agent support.

**Comment by tigattack** [comment]
Let me know if you have any further questions or issues with this.

**Comment by TheFrodo** [comment]
Hello, I'm opening this up again.
I have now installed Powershell and the script, only when I want to run the script I get the error: "The specified module 'Veeam.Backup.PowerShell' was not loaded because no valid module file was found in any module directory."

**Comment by TheFrodo** [comment]
I should have mentioned that I installed the whole thing on Ubuntu 22.04 LTS.
and the Veeam Agent, and it is through this that the backup is created.

I also attach the log here

[2023-05-03_08.47.23_Bootstrap.log](https://github.com/tigattack/VeeamNotify/files/11380101/2023-05-03_08.47.23_Bootstrap.log)

**Comment by tigattack** [comment]
Sorry, VeeamNotify can't be run on a Linux Agent. As described in the README, it only supports running on Agent jobs which are managed by the Backup & Replication server. You can see a description of the differences [in the docs](https://helpcenter.veeam.com/docs/backup/agents/agent_job_protection_mode.html?ver=120#selecting-job-mode).

The reason for this is when the job is managed by the agent rather than the server, everything is executed on the agent/client side, including any pre- and post-scripts. The Agent doesn't ship with the Veeam PowerShell module (as described in the error you provided), so VeeamNotify cannot function in this scenario.
